AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SEGG
Resources:
  getStepFunctionData:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: /lambda/getStepFunctions
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
                - states:ListStateMachines
                - states:DescribeStateMachine
              Resource: "*"
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /getStepFunctionData
            Method: get
